-- 在 Supabase Dashboard -> SQL Editor 中执行本文件。
create extension if not exists pgcrypto;

create table if not exists public.wechat_accounts (
    id uuid primary key default gen_random_uuid(),
    name text not null unique,
    account_type text not null default 'personal_subscription'
        check (account_type in ('personal_subscription', 'verified_subscription', 'service_account')),
    api_enabled boolean not null default false,
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now()
);

create table if not exists public.articles (
    id uuid primary key default gen_random_uuid(),
    account_id uuid not null references public.wechat_accounts(id) on delete cascade,
    source_key text not null,
    external_id text,
    title text not null,
    url text,
    digest text,
    publish_time timestamptz not null,
    category text,
    data_source text not null default 'manual_import'
        check (data_source in ('manual_import', 'wechat_api')),
    collected_at timestamptz not null default now(),
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now(),
    unique (account_id, source_key)
);

create table if not exists public.article_stats (
    id bigint generated by default as identity primary key,
    article_id uuid not null references public.articles(id) on delete cascade,
    stat_date date not null,
    views integer check (views is null or views >= 0),
    read_users integer check (read_users is null or read_users >= 0),
    likes integer check (likes is null or likes >= 0),
    recommendations integer check (recommendations is null or recommendations >= 0),
    shares integer check (shares is null or shares >= 0),
    comments integer check (comments is null or comments >= 0),
    new_followers integer,
    data_source text not null default 'manual_import'
        check (data_source in ('manual_import', 'wechat_api')),
    collected_at timestamptz not null default now(),
    imported_at timestamptz not null default now(),
    unique (article_id, stat_date)
);

create table if not exists public.user_stats (
    id bigint generated by default as identity primary key,
    account_id uuid not null references public.wechat_accounts(id) on delete cascade,
    stat_date date not null,
    new_followers integer,
    cancel_followers integer,
    net_followers integer,
    data_source text not null default 'manual_import'
        check (data_source in ('manual_import', 'wechat_api')),
    collected_at timestamptz not null default now(),
    imported_at timestamptz not null default now(),
    unique (account_id, stat_date)
);

create table if not exists public.account_content_stats (
    id bigint generated by default as identity primary key,
    account_id uuid not null references public.wechat_accounts(id) on delete cascade,
    stat_date date not null,
    publish_count integer check (publish_count is null or publish_count >= 0),
    share_users integer check (share_users is null or share_users >= 0),
    favorite_users integer check (favorite_users is null or favorite_users >= 0),
    original_read_users integer check (original_read_users is null or original_read_users >= 0),
    data_source text not null default 'manual_import'
        check (data_source in ('manual_import', 'wechat_api')),
    collected_at timestamptz not null default now(),
    created_at timestamptz not null default now(),
    unique (account_id, stat_date)
);

create table if not exists public.article_channels (
    id bigint generated by default as identity primary key,
    article_id uuid not null references public.articles(id) on delete cascade,
    stat_date date not null,
    channel text not null check (char_length(btrim(channel)) > 0),
    read_users integer check (read_users is null or read_users >= 0),
    read_percent numeric(12, 10)
        check (read_percent is null or (read_percent >= 0 and read_percent <= 1)),
    data_source text not null default 'manual_import'
        check (data_source in ('manual_import', 'wechat_api')),
    collected_at timestamptz not null default now(),
    created_at timestamptz not null default now(),
    unique (article_id, stat_date, channel)
);

create table if not exists public.account_daily_stats (
    id bigint generated by default as identity primary key,
    account_id uuid not null references public.wechat_accounts(id) on delete cascade,
    stat_date date not null,
    views integer check (views is null or views >= 0),
    shares integer check (shares is null or shares >= 0),
    favorites integer check (favorites is null or favorites >= 0),
    publish_count integer check (publish_count is null or publish_count >= 0),
    data_source text not null default 'manual_import'
        check (data_source in ('manual_import', 'wechat_api')),
    collected_at timestamptz not null default now(),
    created_at timestamptz not null default now(),
    unique (account_id, stat_date)
);

create table if not exists public.article_channel_stats (
    id bigint generated by default as identity primary key,
    article_id uuid not null references public.articles(id) on delete cascade,
    channel text not null check (char_length(btrim(channel)) > 0),
    read_users integer check (read_users is null or read_users >= 0),
    read_percent numeric(12, 10)
        check (read_percent is null or (read_percent >= 0 and read_percent <= 1)),
    stat_date date not null,
    data_source text not null default 'manual_import'
        check (data_source in ('manual_import', 'wechat_api')),
    collected_at timestamptz not null default now(),
    created_at timestamptz not null default now(),
    unique (article_id, channel, stat_date)
);

create table if not exists public.import_runs (
    id uuid primary key default gen_random_uuid(),
    account_id uuid not null references public.wechat_accounts(id) on delete cascade,
    file_name text not null,
    file_hash text not null,
    status text not null check (status in ('running', 'success', 'failed', 'skipped')),
    rows_received integer not null default 0,
    rows_imported integer not null default 0,
    error_message text,
    created_at timestamptz not null default now(),
    completed_at timestamptz,
    unique (account_id, file_hash)
);

create table if not exists public.sync_runs (
    id uuid primary key default gen_random_uuid(),
    account_id uuid references public.wechat_accounts(id) on delete cascade,
    sync_type text not null,
    status text not null check (status in ('running', 'success', 'failed', 'permission_denied')),
    rows_synced integer not null default 0,
    provider_error_code text,
    error_message text,
    started_at timestamptz not null default now(),
    completed_at timestamptz
);

create index if not exists idx_articles_account_publish
    on public.articles(account_id, publish_time desc);
create index if not exists idx_article_stats_date
    on public.article_stats(stat_date desc);
create index if not exists idx_user_stats_account_date
    on public.user_stats(account_id, stat_date desc);
create index if not exists idx_account_content_stats_date
    on public.account_content_stats(stat_date desc);
create index if not exists idx_article_channels_date
    on public.article_channels(stat_date desc);
create index if not exists idx_article_channels_channel
    on public.article_channels(channel);
create index if not exists idx_account_daily_stats_account_date
    on public.account_daily_stats(account_id, stat_date desc);
create index if not exists idx_article_channel_stats_article_date
    on public.article_channel_stats(article_id, stat_date desc);
create index if not exists idx_article_channel_stats_channel
    on public.article_channel_stats(channel);
create index if not exists idx_account_daily_stats_latest
    on public.account_daily_stats(account_id, stat_date desc, collected_at desc);
create index if not exists idx_article_stats_latest
    on public.article_stats(stat_date desc, collected_at desc);

create or replace function public.set_updated_at()
returns trigger language plpgsql as $$
begin
    new.updated_at = now();
    return new;
end;
$$;

drop trigger if exists set_wechat_accounts_updated_at on public.wechat_accounts;
create trigger set_wechat_accounts_updated_at
before update on public.wechat_accounts
for each row execute function public.set_updated_at();

drop trigger if exists set_articles_updated_at on public.articles;
create trigger set_articles_updated_at
before update on public.articles
for each row execute function public.set_updated_at();

-- 生产表不对 anon/authenticated 开放；service_role 会绕过 RLS。
alter table public.wechat_accounts enable row level security;
alter table public.articles enable row level security;
alter table public.article_stats enable row level security;
alter table public.user_stats enable row level security;
alter table public.account_content_stats enable row level security;
alter table public.article_channels enable row level security;
alter table public.account_daily_stats enable row level security;
alter table public.article_channel_stats enable row level security;
alter table public.import_runs enable row level security;
alter table public.sync_runs enable row level security;
