-- 为现有 Supabase 项目增加公众号每日内容数据和文章阅读渠道数据。
-- 本迁移可重复执行，不修改或删除现有表和数据。

create table if not exists public.account_content_stats (
    id bigint generated by default as identity primary key,
    account_id uuid not null references public.wechat_accounts(id) on delete cascade,
    stat_date date not null,
    publish_count integer check (publish_count is null or publish_count >= 0),
    share_users integer check (share_users is null or share_users >= 0),
    favorite_users integer check (favorite_users is null or favorite_users >= 0),
    original_read_users integer check (original_read_users is null or original_read_users >= 0),
    data_source text not null default 'manual_import'
        check (data_source in ('manual_import', 'wechat_api')),
    created_at timestamptz not null default now(),
    unique (account_id, stat_date)
);

create table if not exists public.article_channels (
    id bigint generated by default as identity primary key,
    article_id uuid not null references public.articles(id) on delete cascade,
    stat_date date not null,
    channel text not null check (char_length(btrim(channel)) > 0),
    read_users integer check (read_users is null or read_users >= 0),
    read_percent numeric(12, 10)
        check (read_percent is null or (read_percent >= 0 and read_percent <= 1)),
    data_source text not null default 'manual_import'
        check (data_source in ('manual_import', 'wechat_api')),
    created_at timestamptz not null default now(),
    unique (article_id, stat_date, channel)
);

create index if not exists idx_account_content_stats_date
    on public.account_content_stats(stat_date desc);
create index if not exists idx_article_channels_date
    on public.article_channels(stat_date desc);
create index if not exists idx_article_channels_channel
    on public.article_channels(channel);

-- 与现有生产表一致：不向 anon/authenticated 创建策略；service_role 绕过 RLS。
alter table public.account_content_stats enable row level security;
alter table public.article_channels enable row level security;
