-- 新增账号每日数据与单篇文章渠道数据；保留现有表不变。
create table if not exists public.account_daily_stats (
    id bigint generated by default as identity primary key,
    account_id uuid not null references public.wechat_accounts(id) on delete cascade,
    stat_date date not null,
    views integer check (views is null or views >= 0),
    shares integer check (shares is null or shares >= 0),
    favorites integer check (favorites is null or favorites >= 0),
    publish_count integer check (publish_count is null or publish_count >= 0),
    data_source text not null default 'manual_import'
        check (data_source in ('manual_import', 'wechat_api')),
    created_at timestamptz not null default now(),
    unique (account_id, stat_date)
);

create table if not exists public.article_channel_stats (
    id bigint generated by default as identity primary key,
    article_id uuid not null references public.articles(id) on delete cascade,
    channel text not null check (char_length(btrim(channel)) > 0),
    read_users integer check (read_users is null or read_users >= 0),
    read_percent numeric(12, 10)
        check (read_percent is null or (read_percent >= 0 and read_percent <= 1)),
    stat_date date not null,
    data_source text not null default 'manual_import'
        check (data_source in ('manual_import', 'wechat_api')),
    created_at timestamptz not null default now(),
    unique (article_id, channel, stat_date)
);

create index if not exists idx_account_daily_stats_account_date
    on public.account_daily_stats(account_id, stat_date desc);
create index if not exists idx_article_channel_stats_article_date
    on public.article_channel_stats(article_id, stat_date desc);
create index if not exists idx_article_channel_stats_channel
    on public.article_channel_stats(channel);

alter table public.account_daily_stats enable row level security;
alter table public.article_channel_stats enable row level security;

grant select, insert, update, delete
on table public.account_daily_stats, public.article_channel_stats
to service_role;

revoke all privileges
on table public.account_daily_stats, public.article_channel_stats
from anon, authenticated;
